### ISSUE TITLE
dist contains no build

### ISSUE THREAD

**Issue by DimitarChristoff** [snowcoders/react-popper#7]
npm install just brings you in your src files, it's pointless if your local codebase is not with TS. 

```sh
node_modules/@snowcoders/react-popper/dist/Arrow.d.ts
node_modules/@snowcoders/react-popper/dist/index.d.ts
node_modules/@snowcoders/react-popper/dist/index.js
node_modules/@snowcoders/react-popper/dist/Manager.d.ts
node_modules/@snowcoders/react-popper/dist/Popper.d.ts
node_modules/@snowcoders/react-popper/dist/Target.d.ts
``` 

which also means popper.js is not resolved. this is a semantically invalid npm package.

**Comment by k2snowman69** [comment]
The index.js file is the library compiled into a single file the source files are all typescript, so it compiles into the index.js. The d.ts files are just definition files that are also from the build output; they are useful if you work in typescript. If you're using babel or typescript you should be able to just use an es6 import of `@snowcoders/react-popper` and the path should resolve. 

If you're in es5, you should be able to bring in the index.js file directly: import * from '@snowcoders/react-popper/dist/index.js'

About it not resolving popper.js. This package peer-depends on popper.js which if you're using a nested package structure allows you to pick the version of popper.js you wish to use. If you always know you want to use the latest of both popper.js and react-popper, likely the official react-popper from FezVrasta is more applicable for you: https://github.com/FezVrasta/react-popper

I hope that helps!

**Comment by DimitarChristoff** [comment]
i get that - but the UMD factory reads:

 ```js
module.exports = factory(require("tslib"), require("react"), require("react-dom"), require("popper.js"));
```

so basically, the compiled runtime needs tslib? 

https://github.com/snowcoders/react-popper/blob/master/package.json#L43-L47

does that not defeat the point of a build...

**Comment by k2snowman69** [comment]
`tslib` is a runtime library for typescript, it is not the entire typescript build process (which is the npm package `typescript`). It basically contains helper functions that javascript output from the typescript build process uses when extending, assigning and manipulating objects. Instead of packaging it inside of this library, it's extracted with the `--importHelpers` flag provided by typescript; this way when you have multiple typescript packages, you aren't adding those helpers per library, thus saving what can add up to be a few kbs of download size.

Something we could consider is seeing if tslib is still needed if we push the build output to es6 but as of right now, the current output needs the tslib runtime library.

**Comment by DimitarChristoff** [comment]
There are a lot of ts projects that are compiled down to es5 without the need for that dependency - eg, blueprintjs is fine to consume in a regular project. 

Anyway - thanks, I think the abstraction is thin enough so I will wrap my own popper

**Comment by k2snowman69** [comment]
I'll take a look at blueprintjs and see how it's done! I clearly may have just missed something important there. I'm currently in Europe so it maybe until the weekend until I can take a look but I'll try and do some research to see what's going on there.

Thanks for the information! I'm going to leave this open as a tracker for that investigation.

**Comment by k2snowman69** [comment]
Looked into Blueprint.js and it does also has a dependency on tslib. I've went through a few packages to get exact line numbers for these dependencies:
https://github.com/palantir/blueprint/blob/develop/packages/select/package.json#L38
https://github.com/palantir/blueprint/blob/develop/packages/table/package.json#L39

That said, when they perform the webpack build, they haven't listed tslib as an external dependency so it's actually being packaged in the distribution code which isn't actually ideal for intermediary libraries since this will result in multiple tslibs being packaged.

To get more context from Blueprint.js I've opened feature request on blueprint to figure out why tslib isn't an external dependency
https://github.com/palantir/blueprint/issues/2548

Based on what comes out of this feature, I may or may not include tslib into the package

**Comment by k2snowman69** [comment]
Looks like they are going to externalize it in the 3.0.0 milestone. Closing this as it will align after that is resolved.
